# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_auto_20171031_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Provincia')),
            ],
            options={
                'abstract': False,
                'permissions': (('puede_ver', 'puede ver'),),
            },
        ),
    ]
