# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('iniciales', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
                'permissions': (('puede_ver', 'puede ver'),),
            },
        ),
    ]
