# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0004_auto_20171114_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={},
        ),
    ]
