# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0005_auto_20171127_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nit',
            new_name='rnc',
        ),
    ]
