# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0002_auto_20171114_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Capitulo')),
            ],
            options={
                'abstract': False,
                'permissions': (('puede_ver', 'puede ver'),),
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Capitulo')),
            ],
            options={
                'abstract': False,
                'permissions': (('puede_ver', 'puede ver'),),
            },
        ),
    ]
