# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0005_detallelevantamiento_soportenc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levantamiento',
            name='lote',
        ),
        migrations.AddField(
            model_name='apoyo',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Proyecto'),
        ),
    ]
