# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0006_auto_20171115_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apoyo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='capitulo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='circuito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='defecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='levantamiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='norma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipodato',
            options={},
        ),
        migrations.RemoveField(
            model_name='apoyo',
            name='lote',
        ),
        migrations.AddField(
            model_name='circuito',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Proyecto'),
        ),
    ]
