# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0005_auto_20171127_2255'),
        ('levantamiento', '0007_auto_20171122_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuito',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='levantamiento',
            name='empresa',
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='longitudPlano',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='levantamiento',
            name='terreno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='NumeroDePoligonos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Empresa'),
        ),
        migrations.AlterField(
            model_name='levantamiento',
            name='poligono',
            field=models.IntegerField(default=0),
        ),
    ]
