# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0008_auto_20171127_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='apoyo',
            name='circuito',
        ),
        migrations.RemoveField(
            model_name='levantamiento',
            name='inspeccion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='NumeroDePoligonos',
        ),
        migrations.AddField(
            model_name='apoyo',
            name='lote',
            field=models.ManyToManyField(to='levantamiento.Proyecto'),
        ),
        migrations.RemoveField(
            model_name='circuito',
            name='lote',
        ),
        migrations.AddField(
            model_name='circuito',
            name='lote',
            field=models.ManyToManyField(null=True, to='levantamiento.Proyecto'),
        ),
        migrations.AddField(
            model_name='poligono',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Proyecto'),
        ),
    ]
