# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0010_auto_20171129_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levantamiento',
            name='poligono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='levantamiento.Poligono'),
        ),
    ]
