# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levantamiento', '0011_auto_20171130_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelevantamiento',
            name='valor',
            field=models.CharField(choices=[('C', 'Conforme'), ('NC', 'NoConforme'), ('N/A', 'No Aplica')], default='N/A', max_length=50),
        ),
    ]
